import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Heart, Albums, Gallery } from "@/components/svgs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function SideMenu() {
  return (
    <div className="pb-12">
      <div className="space-y-4 py-4">
        <div className="px-3 py-2">
          <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
            Manage
          </h2>
          <div className="space-y-1">
            <Link href={"/gallery"}>
              <Button variant="ghost" className="w-full justify-start">
                <Gallery />
                Image Gallery
              </Button>
            </Link>
            <Button variant="ghost" className="w-full justify-start">
              <Albums />
              Albums
            </Button>
            <Link href={"/favorites"}>
              <Button variant="ghost" className="w-full justify-start">
                <Heart />
                Favorites
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark h-full">
      <body className={`${inter.className} h-full overflow-hidden`}>
        <div className="border-b">
          <div className="flex h-16 items-center px-4 container mx-auto">
            <h4 className="uppercase text-lg font-semibold tracking-tight">
              Photos App
            </h4>
            {/* <TeamSwitcher /> */}
            {/* <MainNav className="mx-6" /> */}
            <div className="ml-auto flex items-center space-x-4">
              <Avatar>
                <AvatarImage src="https://github.com/shadcn.png" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>

              {/* <Search /> */}
              {/* <UserNav /> */}
            </div>
          </div>
        </div>
        <div className="border-t h-full">
          <div className="bg-background h-full">
            <div className="grid lg:grid-cols-5 h-full">
              <SideMenu />
              <div className="col-span-3 lg:col-span-4 lg:border-l">
                {children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
